inputs:
  registry:
    default: registry.speechanddebate.org
  image:
    description: 'The docker image'
    required: true
  registry_username:
    required: true
  registry_password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to registry
      run: |
        echo "${{ inputs.registry_password }}" |
          docker ${{ inputs.registry }} \
            --username "${{ inputs.registry_username }}" \
            --password-stdin

    - name: Push image
      run: |
        docker push --all-tags "${{ inputs.registry }}/${{ inputs.image }}"
