inputs:
  image:
    description: 'The docker image'
    required: true
  registry_username:
    required: true
  registry_password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to registry
      run: |
        echo "${{ inputs.registry_password }}" |
          docker login "$REGISTRY" \
            --username "${{ inputs.registry_username }}" \
            --password-stdin

    - name: Push image
      run: |
        docker push --all-tags "$REGISTRY/${{ inputs.image }}"
