#!/bin/sh
#
if ! git diff --cached --quiet -- schemats/; then
    echo "Running schemats checks..."
	cd schemats
    npm run lint || exit 1
fi

if ! git diff --cached --quiet -- indexcards/; then
    echo "Running indexcards checks..."
	cd indexcards
    npm run lint || exit 1
    npm run typecheck || exit 1
	echo "Updating openapi.json..."
	npm run build:openapi --workspace=indexcards
	git  add **/openapi.json
fi
