#!/bin/sh
set -e
echo "Linting..."
npm run lint
echo "Typecheck..."
# schemats super fails typecheck right now
npm run typecheck --workspace=indexcards

echo "Updating openapi.json..."
npm run build:openapi --workspace=indexcards
git  add indexcards/api/routes/openapi/openapi.json

