#!/bin/sh
set -e
echo "Linting"
npm run lint
echo "Typecheck"
npm run typecheck

echo "Updating openapi.json"
npm run build:openapi --workspace=indexcards
git  add indexcards/api/routes/openapi/openapi.json

