name: Build

on:
  # manual trigger for emergencies
  workflow_dispatch:
  # called by ci.yml once all checks pass on main
  workflow_call:

jobs:
  build-indexcards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        uses: ./.forgejo/actions/docker-build
        with:
          image: indexcards
          dockerfile: indexcards/Dockerfile

      - name: Publish image
        uses: ./.forgejo/actions/docker-publish
        with:
          image: indexcards
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}

  build-schemats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        uses: ./.forgejo/actions/docker-build
        with:
          image: schemats
          dockerfile: schemats/Dockerfile

      - name: Publish image
        uses: ./.forgejo/actions/docker-publish
        with:
          image: schemats
          registry_username: ${{ secrets.REGISTRY_USERNAME }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD }}
