name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE: registry.speechanddebate.org/indexcards

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build image
        run: |
          docker build \
            -f indexcards/Dockerfile \
            -t "$IMAGE:${FORGEJO_SHA}" \
            -t "$IMAGE:production" \
            .

  publish:
      runs-on: linux-amd64
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v6
        - uses: ./.forgejo/actions/docker-publish
          with:
            image: indexcards
            registry_username: ${{ secrets.REGISTRY_USERNAME }}
            registry_password: ${{ secrets.REGISTRY_PASSWORD }}
