name: Indexcards CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE: registry.speechanddebate.org/indexcards-ci

jobs:
  ci:
    name: CI
    runs-on: linux-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build CI image
        run: |
          docker build \
            -f indexcards/Dockerfile \
            --target dev \
            -t "${IMAGE}:${FORGEJO_SHA}" \
            .

      - name: Lint
        run: |
          docker run --rm \
            "${IMAGE}:${FORGEJO_SHA}" \
            npm run lint

      - name: Typecheck
        run: |
          docker run --rm \
            "${IMAGE}:${FORGEJO_SHA}" \
            npm run typecheck

      - name: Test
        run: |
          docker run --rm \
            -v "$PWD/.forgejo/config/config.ci.json:/config/config.json:ro" \
            "${IMAGE}:${FORGEJO_SHA}" \
            npm run test-ci
