name: Indexcards CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: linux-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy Indexcards Config
        run: |
          cp .forgejo/config/config.ci.json indexcards/config/config.json
      - name: Lint
        run: |
            npm run lint --workspace=indexcards

      - name: Typecheck
        run: |
            npm run typecheck --workspace=indexcards

      - name: Test
        run: |
            npm run test-ci --workspace=indexcards
