name: Indexcards CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: linux-amd64
    services:
      mariadb:
        image: mariadb:12
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: tabroom
          MARIADB_USER: root
          MARIADB_PASSWORD: tabroom
        volumes:
          - indexcards/tests/test.sql:/docker-entrypoint-initdb.d/seed.sql:ro
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
          --health-start-period=10s

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Copy indexcards config
        run: |
          cp .forgejo/config/config.ci.json indexcards/config/config.json

      - name: Install dependancies
        run: |
            npm ci

      - name: Lint
        run: |
            npm run lint --workspace=indexcards

      - name: Typecheck
        run: |
            npm run typecheck --workspace=indexcards

      - name: Test
        run: |
            npm run test-ci --workspace=indexcards
