/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The result of a person claiming a judge or student record
 */
export interface ClaimResponse {
	/** A message indicating the claim request was submitted */
	message: string;
	/** Additional details about the claim request submission */
	detail: string;
}
