/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The count of unread messages for the logged in user
 */
export interface InboxUnreadCount {
	/**
	 * The number of unread messages
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	count: number;
}
