/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ParadigmSearchResultSchoolsItem } from './paradigmSearchResultSchoolsItem';

/**
 * A judge matching a paradigm search
 */
export interface ParadigmSearchResult {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	/** Full name */
	name: string;
	/**
	 * Number of tournaments judged
	 * @minimum 0
	 * @maximum 9007199254740991
	 */
	tournJudged: number;
	schools: ParadigmSearchResultSchoolsItem[];
}
