/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type PersonTournSummaryLivedocsItem = {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	categoryId: number;
	/** @nullable */
	categoryName: string | null;
	url: string;
	/** @nullable */
	caption: string | null;
};
