/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { PersonTournSummaryLivedocsItem } from './personTournSummaryLivedocsItem';
import type { PersonTournSummaryRolesItem } from './personTournSummaryRolesItem';

/**
 * A summary of a tourn and a persons role in it for the user homepage
 */
export interface PersonTournSummary {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	roles: PersonTournSummaryRolesItem[];
	livedocs: PersonTournSummaryLivedocsItem[];
}
