/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * Settings keyed by tag
 */
export type PersonOutputSettings = {
	[key: string]:
		| string
		| number
		| boolean
		| null
		| { [key: string]: unknown }
		| unknown[];
} | null;
