/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * Additional details about the error, such as validation issues.
 */
export type ProblemSchemaIssues = { [key: string]: unknown };
