/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ProblemSchemaIssues } from './problemSchemaIssues';

export interface ProblemSchema {
	/** A URI reference that identifies the problem type. */
	type: string;
	/** A short, human-readable summary of the problem type. */
	title: string;
	/**
	 * The HTTP status code.
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	status: number;
	/** Human-readable explanation of the error. */
	detail?: string;
	/** A URI reference to the specific occurrence. */
	instance?: string;
	/** Additional details about the error, such as validation issues. */
	issues?: ProblemSchemaIssues;
}
