/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { PersonQuizOutput } from './personQuizOutput';
import type { QuizBadgeOutput } from './quizBadgeOutput';

export interface QuizOutput {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	tag: string | null;
	label: string | null;
	description: string | null;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	sitewide: number;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	hidden: number;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	approval: number;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	show_answers: number;
	/**
	 * @minimum -9007199254740991
	 * @maximum 9007199254740991
	 */
	admin_only: number;
	circuit: number | null;
	Badge: QuizBadgeOutput;
	PersonQuizzes?: PersonQuizOutput[];
}
