/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

export type ResultSetSchemaEvent = {
	/**
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	id: number;
	abbr: string;
	level: string;
	name: string;
	/**
	 * Absent when the event has no NSDA category
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	nsdacategory?: number;
	type: string;
};
