/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */
import type { ChapterSchema } from './chapterSchema';
import type { PersonOutput } from './personOutput';
import type { StudentSchemaMetadata } from './studentSchemaMetadata';
import type { StudentSchemaSettings } from './studentSchemaSettings';
import type { StudentSchemaSettingsTimestamps } from './studentSchemaSettingsTimestamps';

export interface StudentSchema {
	/**
	 * Unique identifier for the student
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	readonly id: number;
	/**
	 * First name of the student
	 * @nullable
	 */
	first?: string | null;
	/**
	 * Middle name of the student
	 * @nullable
	 */
	middle?: string | null;
	/**
	 * Last name of the student
	 * @nullable
	 */
	last?: string | null;
	/**
	 * Pronunciation guide
	 * @nullable
	 */
	phonetic?: string | null;
	/**
	 * Full Year of student graduation
	 * @nullable
	 */
	gradYear?: number | null;
	/** Whether the student is a novice */
	novice?: boolean;
	/** Whether the student is retired */
	retired?: boolean;
	/**
	 * Student gender
	 * @nullable
	 */
	gender?: string | null;
	/**
	 * NSDA Member ID Number
	 * @nullable
	 */
	nsda?: number | null;
	/**
	 * Chapter School that the student belongs to
	 * @maximum 9007199254740991
	 * @exclusiveMinimum 0
	 */
	chapterId: number;
	/** Tabroom Person the student is linked to */
	personId?: number | null;
	Chapter?: ChapterSchema;
	Person?: PersonOutput;
	/** Creation timestamp */
	readonly createdAt: string;
	/** Settings keyed by tag */
	settings?: StudentSchemaSettings;
	/** Setting created_at and timestamp values keyed by tag */
	settingsTimestamps?: StudentSchemaSettingsTimestamps;
	/** Additional metadata for the student */
	metadata?: StudentSchemaMetadata;
}
