/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * Setting created_at and timestamp values keyed by tag
 */
export type TournSettingsTimestamps = {
	[key: string]: {
		created_at?: string | null;
		timestamp?: string | null;
	};
} | null;
