/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * IndexCards API
 * Tabroom.com data & operational API
 * OpenAPI spec version: 1.2.0
 */

/**
 * The paradigm of the logged in user
 */
export interface UserParadigmOutput {
	/**
	 * The paradigm for the logged in user
	 * @maxLength 65535
	 */
	paradigm: string;
}
